# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embeddings/embeddings.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x65mbeddings/embeddings.proto\x12\tembedding\"\"\n\x10\x45mbeddingRequest\x12\x0e\n\x06inputs\x18\x01 \x03(\t\"\x1e\n\tEmbedding\x12\x11\n\tembedding\x18\x01 \x03(\x02\"=\n\x11\x45mbeddingResponse\x12(\n\nembeddings\x18\x01 \x03(\x0b\x32\x14.embedding.Embedding2a\n\x11\x45mbeddingsService\x12L\n\x0f\x43reateEmbedding\x12\x1b.embedding.EmbeddingRequest\x1a\x1c.embedding.EmbeddingResponseB<Z:github.com/defenseunicorns/leapfrogai/pkg/client/embeddingb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embeddings.embeddings_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z:github.com/defenseunicorns/leapfrogai/pkg/client/embedding'
  _EMBEDDINGREQUEST._serialized_start=42
  _EMBEDDINGREQUEST._serialized_end=76
  _EMBEDDING._serialized_start=78
  _EMBEDDING._serialized_end=108
  _EMBEDDINGRESPONSE._serialized_start=110
  _EMBEDDINGRESPONSE._serialized_end=171
  _EMBEDDINGSSERVICE._serialized_start=173
  _EMBEDDINGSSERVICE._serialized_end=270
# @@protoc_insertion_point(module_scope)
