# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embeddings/embeddings.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x65mbeddings/embeddings.proto\x12\tembedding\"\"\n\x10\x45mbeddingRequest\x12\x0e\n\x06inputs\x18\x01 \x03(\t\"\'\n\x11\x45mbeddingResponse\x12\x12\n\nembeddings\x18\x01 \x03(\t2a\n\x11\x45mbeddingsService\x12L\n\x0f\x43reateEmbedding\x12\x1b.embedding.EmbeddingRequest\x1a\x1c.embedding.EmbeddingResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embeddings.embeddings_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMBEDDINGREQUEST._serialized_start=42
  _EMBEDDINGREQUEST._serialized_end=76
  _EMBEDDINGRESPONSE._serialized_start=78
  _EMBEDDINGRESPONSE._serialized_end=117
  _EMBEDDINGSSERVICE._serialized_start=119
  _EMBEDDINGSSERVICE._serialized_end=216
# @@protoc_insertion_point(module_scope)
