# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

import leapfrogai_pb2 as leapfrogai__pb2

GRPC_GENERATED_VERSION = "1.66.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in leapfrogai_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class LLMStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CountTokens = channel.unary_unary(
            "/leapfrogai.LLM/CountTokens",
            request_serializer=leapfrogai__pb2.TokenCountRequest.SerializeToString,
            response_deserializer=leapfrogai__pb2.TokenCountResponse.FromString,
            _registered_method=True,
        )


class LLMServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CountTokens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_LLMServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CountTokens": grpc.unary_unary_rpc_method_handler(
            servicer.CountTokens,
            request_deserializer=leapfrogai__pb2.TokenCountRequest.FromString,
            response_serializer=leapfrogai__pb2.TokenCountResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "leapfrogai.LLM", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("leapfrogai.LLM", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class LLM(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CountTokens(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/leapfrogai.LLM/CountTokens",
            leapfrogai__pb2.TokenCountRequest.SerializeToString,
            leapfrogai__pb2.TokenCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
