# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: leapfrogai_sdk/counting/counting.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n&leapfrogai_sdk/counting/counting.proto\x12\x08\x63ounting"!\n\x11TokenCountRequest\x12\x0c\n\x04text\x18\x01 \x01(\t"#\n\x12TokenCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05"@\n\x10TokenCountResult\x12,\n\x06result\x18\x01 \x01(\x0b\x32\x1c.counting.TokenCountResponse2]\n\x11TokenCountService\x12H\n\x0b\x43ountTokens\x12\x1b.counting.TokenCountRequest\x1a\x1a.counting.TokenCountResult"\x00\x42;Z9github.com/defenseunicorns/leapfrogai/pkg/client/countingb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "leapfrogai_sdk.counting.counting_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = (
        b"Z9github.com/defenseunicorns/leapfrogai/pkg/client/counting"
    )
    _globals["_TOKENCOUNTREQUEST"]._serialized_start = 52
    _globals["_TOKENCOUNTREQUEST"]._serialized_end = 85
    _globals["_TOKENCOUNTRESPONSE"]._serialized_start = 87
    _globals["_TOKENCOUNTRESPONSE"]._serialized_end = 122
    _globals["_TOKENCOUNTRESULT"]._serialized_start = 124
    _globals["_TOKENCOUNTRESULT"]._serialized_end = 188
    _globals["_TOKENCOUNTSERVICE"]._serialized_start = 190
    _globals["_TOKENCOUNTSERVICE"]._serialized_end = 283
# @@protoc_insertion_point(module_scope)
