# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from leapfrogai_sdk.counting import (
    counting_pb2 as leapfrogai__sdk_dot_counting_dot_counting__pb2,
)


class TokenCountServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CountTokens = channel.unary_unary(
            "/counting.TokenCountService/CountTokens",
            request_serializer=leapfrogai__sdk_dot_counting_dot_counting__pb2.TokenCountRequest.SerializeToString,
            response_deserializer=leapfrogai__sdk_dot_counting_dot_counting__pb2.TokenCountResult.FromString,
        )


class TokenCountServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CountTokens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TokenCountServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CountTokens": grpc.unary_unary_rpc_method_handler(
            servicer.CountTokens,
            request_deserializer=leapfrogai__sdk_dot_counting_dot_counting__pb2.TokenCountRequest.FromString,
            response_serializer=leapfrogai__sdk_dot_counting_dot_counting__pb2.TokenCountResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "counting.TokenCountService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class TokenCountService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CountTokens(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/counting.TokenCountService/CountTokens",
            leapfrogai__sdk_dot_counting_dot_counting__pb2.TokenCountRequest.SerializeToString,
            leapfrogai__sdk_dot_counting_dot_counting__pb2.TokenCountResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
