apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: lfai-{{ regexReplaceAll "\\W+|_" .Values.model.name "-" | lower }}-{{ regexReplaceAll "\\W+|_" .Values.model.revision "-" | lower }}
    namespace: leapfrogai
spec:
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass  }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessModes | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
