# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import embeddings_pb2 as embeddings__pb2


class GenerateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEmbedding = channel.unary_unary(
                '/embedding.GenerateService/CreateEmbedding',
                request_serializer=embeddings__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=embeddings__pb2.EmbeddingResponse.FromString,
                )


class GenerateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenerateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEmbedding,
                    request_deserializer=embeddings__pb2.EmbeddingRequest.FromString,
                    response_serializer=embeddings__pb2.EmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embedding.GenerateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GenerateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embedding.GenerateService/CreateEmbedding',
            embeddings__pb2.EmbeddingRequest.SerializeToString,
            embeddings__pb2.EmbeddingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
