# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embeddings.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65mbeddings.proto\x12\tembedding\"\"\n\x10\x45mbeddingRequest\x12\x0e\n\x06inputs\x18\x01 \x03(\t\"\'\n\x11\x45mbeddingResponse\x12\x12\n\nembeddings\x18\x01 \x03(\t2_\n\x0fGenerateService\x12L\n\x0f\x43reateEmbedding\x12\x1b.embedding.EmbeddingRequest\x1a\x1c.embedding.EmbeddingResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embeddings_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMBEDDINGREQUEST._serialized_start=31
  _EMBEDDINGREQUEST._serialized_end=65
  _EMBEDDINGRESPONSE._serialized_start=67
  _EMBEDDINGRESPONSE._serialized_end=106
  _GENERATESERVICE._serialized_start=108
  _GENERATESERVICE._serialized_end=203
# @@protoc_insertion_point(module_scope)
